### ISSUE TITLE
Add ASG Handbook to individual diary entries

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Altis#16]
Source: [ASG Handbook](https://docs.google.com/document/d/1c8-ySqKiXYp0RCOYhqvAfUR_HTvS9A1mWrf5Fzawm1c/edit).

BIS Ref:
[createDiarySubject](https://community.bistudio.com/wiki/createDiarySubject).
[createDiaryRecord](https://community.bistudio.com/wiki/createDiaryRecord).

**Template**
createDiarySubject ["myPage","My page"];
// myPage = variable name for reference.
// My Page = Title of the Entry (as it shows up on the left side of the screen)

createDiaryRecord ["varName", ["Intel", "Lots of text would go here"]];
// varName = variable name for reference in the code
// "Intel" = the name of the sub-title
// "Lots of text would go here" = Where the text goes.

**Comment by jmlane** [comment]
How much of 1fbf5e9 covers the current handbook contents?

**Comment by Diffusion9** [comment]
Latest master has pretty much everything now except the image files which I'll get off deljay at some point and convert to .paa files for inclusion. Handbook also needs some grammatical and formatting checks.

**Comment by jmlane** [comment]
I don't think you need to convert to PAAs necessarily from what I've seen but maybe there is a reason to do that that I'm not aware of?

**Comment by Diffusion9** [comment]
Does not need to be paa, no. jpegs will work fine.

**Comment by austinXmedic** [comment]
the only issue with jpegs is the fact that it might appear as a black rectangle until directX is done converting it in the background.

**Comment by Diffusion9** [comment]
Integrated the latest version provided by deljay. Still needs the reference pictures.
