### ISSUE TITLE
CSAT classes spawning with Tile System

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Altis#2]
**Summary**

Deljay is reporting that CSAT units are spawning and should not be. Found references to CSAT classes in sand_loadoutCreator.sqf. Need to investigate and replace with the correct comps (attached to Trello card).

**Related Files:**

- [ ] sand_loadoutCreator.sqf
- [ ] fn_spawnGroup.sqf
- [ ] fn_createGroup.sqf

**Correct Class List:**

- [ ] I_Soldier_SL_F
- [ ] I_Soldier_TL_F
- [ ] I_Soldier_F
- [ ] I_Soldier_AR_F

**Comment by jmlane** [comment]
I cannot find any CSAT units in the code other than the loadout script, which doesn't seem to interact with the spawning functions.

Any thoughts?

**Comment by Diffusion9** [comment]
If you look in sand_loadoutCreator and check case EAST under switch (_side) do, all the soldier classes prefixed with O_ are CSAT soldier bases. You can find a listing of all EAST faction faction classes on the BISwiki: https://community.bistudio.com/wiki/Arma_3_CfgVehicles_EAST.

With that being said, I've not see any CSAT units spawned myself so I would have to get some more steps to repro.

**Comment by austinXmedic** [comment]
If you go ingame and go to an area of the map that isn't already friendly from being visited so many times you can see it happen. I tried to track down why it was spawning CSAT clothing on the AAF units, but couldn't figure it out. The gear script runs obviously because it gives them the vest and the proper gun but the uniform doesn't come along....

**Comment by austinXmedic** [comment]
Simply changing the 'enemySide' inside the tile system loop in sand_serverPersist seems to of solved the problem at least for me anyways.

**Comment by Diffusion9** [comment]
Closing as fixed.
