### ISSUE TITLE
[Low Priority] - VOIP button spamming

### ISSUE THREAD

**Issue by Diffusion9** [Diffusion9/Sandbox.Altis#20]
Checks for spamming the VOIP button.

General Idea (tweakable): If somebody keys up x times within x seconds, disable their beeps for x time?

**Comment by jmlane** [comment]
Github tip: you can setup labels for priorities instead of adding it to the issue title: https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

**Comment by Diffusion9** [comment]
Technically solved by commit eed61da.
